### ISSUE TITLE
Features are not displayed on Android (Samsung S24)

### ISSUE THREAD

**Issue by artex-x** [kortirso/charkeeper#653]
On the **latest Android version** (tested on **Samsung S24**), **features are not displayed at all** on the character sheet.  
At the same time, the **same character** shows features correctly in the **web version**.

## Expected behavior
- Features should be visible and usable on Android the same way as on the web.

## Actual behavior
- Features section appears empty or missing on Android.
- No issue is observed when opening the character in a browser.

This looks like a mobile-specific rendering or data-loading issue on Android.

https://github.com/user-attachments/assets/9c764868-08f5-4e1d-b109-1b3bb9f2a8c0

**Comment by kortirso** [comment]
fixed, bug was because of old style feature format in database for your homebrew longsword

**Comment by artex-x** [comment]
> fixed, bug was because of old style feature format in database for your homebrew longsword

I still have the same issue, should I wait for the next release?

**Comment by kortirso** [comment]
total mistery, please give me the name of broken character, I'll check on my devices

**Comment by artex-x** [comment]
I tried it on a different device (Android tablet), and it works the same

https://github.com/user-attachments/assets/f1b8b152-7b50-4b26-9ab3-538af0fd0463
